// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7sfzotg7pW2SwX-1Vkf28TXE2zLHW78',
    appId: '1:142325051586:web:7c5e35ab722d9680bc4b5b',
    messagingSenderId: '142325051586',
    projectId: 'shout-60c7f',
    authDomain: 'shout-60c7f.firebaseapp.com',
    storageBucket: 'shout-60c7f.appspot.com',
    measurementId: 'G-J1H98DR14H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFHeTwf3uZJInt9GEEdZy2R91AETrF8n4',
    appId: '1:142325051586:android:64fe940dd7e2cdefbc4b5b',
    messagingSenderId: '142325051586',
    projectId: 'shout-60c7f',
    storageBucket: 'shout-60c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_eVR5DVVUuijlgKOXc1XVtmAnio0xV20',
    appId: '1:142325051586:ios:8aae2d7af06f0c95bc4b5b',
    messagingSenderId: '142325051586',
    projectId: 'shout-60c7f',
    storageBucket: 'shout-60c7f.appspot.com',
    iosBundleId: 'com.example.eventManager',
  );
}
